;; crater-grow.clar
;; Autonomous blockchain infrastructure monitoring platform

;; ===========================
;; CONSTANTS
;; ===========================

(define-constant CONTRACT-OWNER tx-sender)

(define-constant ERR-NOT-AUTHORIZED (err u100))
(define-constant ERR-NODE-NOT-FOUND (err u101))
(define-constant ERR-DAPP-NOT-FOUND (err u102))
(define-constant ERR-INVALID-SCORE (err u103))
(define-constant ERR-ALERT-NOT-FOUND (err u104))
(define-constant ERR-ALREADY-REGISTERED (err u105))

;; Health score thresholds (out of 100)
(define-constant SCORE-HEALTHY u80)
(define-constant SCORE-DEGRADED u50)
;; Below SCORE-DEGRADED is considered critical

;; Supported network IDs
(define-constant NETWORK-ETHEREUM u1)
(define-constant NETWORK-POLYGON u2)
(define-constant NETWORK-ARBITRUM u3)

;; ===========================
;; DATA MAPS AND VARS
;; ===========================

;; Track total registered dApps and nodes
(define-data-var total-dapps uint u0)
(define-data-var total-nodes uint u0)
(define-data-var total-alerts uint u0)

;; Authorized monitoring node operators
(define-map authorized-operators
  { operator: principal }
  { active: bool, registered-at: uint }
)

;; Registered dApps being monitored
(define-map dapps
  { dapp-id: uint }
  {
    owner: principal,
    name: (string-ascii 64),
    network-id: uint,
    health-score: uint,         ;; 0-100
    gas-limit: uint,
    tx-count: uint,
    last-updated: uint,
    active: bool
  }
)

;; Map dApp name to ID for lookup
(define-map dapp-name-to-id
  { name: (string-ascii 64) }
  { dapp-id: uint }
)

;; Monitoring nodes in the distributed network
(define-map monitoring-nodes
  { node-id: uint }
  {
    operator: principal,
    network-id: uint,
    active: bool,
    reports-submitted: uint,
    registered-at: uint
  }
)

;; Predictive alerts generated by the platform
(define-map alerts
  { alert-id: uint }
  {
    dapp-id: uint,
    alert-type: (string-ascii 32),  ;; "gas", "congestion", "downtime", "scaling"
    severity: (string-ascii 16),    ;; "low", "medium", "high", "critical"
    message: (string-ascii 128),
    resolved: bool,
    created-at: uint,
    resolved-at: uint
  }
)

;; Performance metrics per dApp (rolling snapshot)
(define-map performance-metrics
  { dapp-id: uint }
  {
    avg-gas-used: uint,
    peak-tx-per-block: uint,
    failed-tx-count: uint,
    uptime-percent: uint,         ;; 0-100
    last-congestion-block: uint
  }
)

;; Remediation actions logged on-chain
(define-map remediation-log
  { dapp-id: uint, action-index: uint }
  {
    action-type: (string-ascii 32), ;; "gas-adjust", "reroute", "scale"
    old-value: uint,
    new-value: uint,
    performed-at: uint,
    performed-by: principal
  }
)

(define-map dapp-remediation-count
  { dapp-id: uint }
  { count: uint }
)

;; ===========================
;; PRIVATE HELPERS
;; ===========================

(define-private (is-owner)
  (is-eq tx-sender CONTRACT-OWNER)
)

(define-private (is-authorized-operator)
  (match (map-get? authorized-operators { operator: tx-sender })
    entry (get active entry)
    false
  )
)

(define-private (is-dapp-owner (dapp-id uint))
  (match (map-get? dapps { dapp-id: dapp-id })
    dapp (is-eq tx-sender (get owner dapp))
    false
  )
)

(define-private (score-to-status (score uint))
  (if (>= score SCORE-HEALTHY)
    "healthy"
    (if (>= score SCORE-DEGRADED)
      "degraded"
      "critical"
    )
  )
)

(define-private (get-next-dapp-id)
  (let ((current (var-get total-dapps)))
    (var-set total-dapps (+ current u1))
    (+ current u1)
  )
)

(define-private (get-next-node-id)
  (let ((current (var-get total-nodes)))
    (var-set total-nodes (+ current u1))
    (+ current u1)
  )
)

(define-private (get-next-alert-id)
  (let ((current (var-get total-alerts)))
    (var-set total-alerts (+ current u1))
    (+ current u1)
  )
)

;; ===========================
;; OPERATOR MANAGEMENT
;; ===========================

;; Register a new authorized monitoring node operator (owner only)
(define-public (register-operator (operator principal))
  (begin
    (asserts! (is-owner) ERR-NOT-AUTHORIZED)
    (asserts!
      (is-none (map-get? authorized-operators { operator: operator }))
      ERR-ALREADY-REGISTERED
    )
    (map-set authorized-operators
      { operator: operator }
      { active: true, registered-at: block-height }
    )
    (ok true)
  )
)

;; Deactivate an operator (owner only)
(define-public (deactivate-operator (operator principal))
  (begin
    (asserts! (is-owner) ERR-NOT-AUTHORIZED)
    (match (map-get? authorized-operators { operator: operator })
      entry
        (begin
          (map-set authorized-operators
            { operator: operator }
            (merge entry { active: false })
          )
          (ok true)
        )
      ERR-NOT-AUTHORIZED
    )
  )
)

;; ===========================
;; DAPP REGISTRATION
;; ===========================

;; Register a dApp for monitoring
(define-public (register-dapp
    (name (string-ascii 64))
    (network-id uint)
    (initial-gas-limit uint))
  (let ((dapp-id (get-next-dapp-id)))
    (asserts!
      (is-none (map-get? dapp-name-to-id { name: name }))
      ERR-ALREADY-REGISTERED
    )
    (map-set dapps
      { dapp-id: dapp-id }
      {
        owner: tx-sender,
        name: name,
        network-id: network-id,
        health-score: u100,
        gas-limit: initial-gas-limit,
        tx-count: u0,
        last-updated: block-height,
        active: true
      }
    )
    (map-set dapp-name-to-id { name: name } { dapp-id: dapp-id })
    (map-set performance-metrics
      { dapp-id: dapp-id }
      {
        avg-gas-used: u0,
        peak-tx-per-block: u0,
        failed-tx-count: u0,
        uptime-percent: u100,
        last-congestion-block: u0
      }
    )
    (map-set dapp-remediation-count { dapp-id: dapp-id } { count: u0 })
    (ok dapp-id)
  )
)

;; Deactivate a dApp from monitoring (owner or dApp owner)
(define-public (deactivate-dapp (dapp-id uint))
  (begin
    (asserts!
      (or (is-owner) (is-dapp-owner dapp-id))
      ERR-NOT-AUTHORIZED
    )
    (match (map-get? dapps { dapp-id: dapp-id })
      dapp
        (begin
          (map-set dapps
            { dapp-id: dapp-id }
            (merge dapp { active: false })
          )
          (ok true)
        )
      ERR-DAPP-NOT-FOUND
    )
  )
)

;; ===========================
;; MONITORING NODE MANAGEMENT
;; ===========================

;; Register a monitoring node (authorized operators only)
(define-public (register-node (network-id uint))
  (begin
    (asserts! (is-authorized-operator) ERR-NOT-AUTHORIZED)
    (let ((node-id (get-next-node-id)))
      (map-set monitoring-nodes
        { node-id: node-id }
        {
          operator: tx-sender,
          network-id: network-id,
          active: true,
          reports-submitted: u0,
          registered-at: block-height
        }
      )
      (ok node-id)
    )
  )
)

;; ===========================
;; HEALTH SCORE REPORTING
;; ===========================

;; Submit a health score update for a dApp (authorized operators only)
(define-public (submit-health-report
    (dapp-id uint)
    (node-id uint)
    (new-health-score uint)
    (avg-gas-used uint)
    (peak-tx-per-block uint)
    (failed-tx-count uint)
    (uptime-percent uint))
  (begin
    (asserts! (is-authorized-operator) ERR-NOT-AUTHORIZED)
    (asserts! (<= new-health-score u100) ERR-INVALID-SCORE)
    (asserts! (<= uptime-percent u100) ERR-INVALID-SCORE)
    (match (map-get? dapps { dapp-id: dapp-id })
      dapp
        (begin
          ;; Update dApp health score and tx count
          (map-set dapps
            { dapp-id: dapp-id }
            (merge dapp {
              health-score: new-health-score,
              tx-count: (+ (get tx-count dapp) u1),
              last-updated: block-height
            })
          )
          ;; Update performance metrics
          (map-set performance-metrics
            { dapp-id: dapp-id }
            {
              avg-gas-used: avg-gas-used,
              peak-tx-per-block: peak-tx-per-block,
              failed-tx-count: failed-tx-count,
              uptime-percent: uptime-percent,
              last-congestion-block:
                (if (< new-health-score SCORE-DEGRADED)
                  block-height
                  (match (map-get? performance-metrics { dapp-id: dapp-id })
                    m (get last-congestion-block m)
                    u0
                  )
                )
            }
          )
          ;; Increment node report counter
          (match (map-get? monitoring-nodes { node-id: node-id })
            node
              (map-set monitoring-nodes
                { node-id: node-id }
                (merge node { reports-submitted: (+ (get reports-submitted node) u1) })
              )
            false
          )
          (ok true)
        )
      ERR-DAPP-NOT-FOUND
    )
  )
)

;; ===========================
;; PREDICTIVE ALERTS
;; ===========================

;; Create a predictive alert for a dApp (authorized operators only)
(define-public (create-alert
    (dapp-id uint)
    (alert-type (string-ascii 32))
    (severity (string-ascii 16))
    (message (string-ascii 128)))
  (begin
    (asserts! (is-authorized-operator) ERR-NOT-AUTHORIZED)
    (asserts! (is-some (map-get? dapps { dapp-id: dapp-id })) ERR-DAPP-NOT-FOUND)
    (let ((alert-id (get-next-alert-id)))
      (map-set alerts
        { alert-id: alert-id }
        {
          dapp-id: dapp-id,
          alert-type: alert-type,
          severity: severity,
          message: message,
          resolved: false,
          created-at: block-height,
          resolved-at: u0
        }
      )
      (ok alert-id)
    )
  )
)

;; Resolve an existing alert (authorized operators or dApp owner)
(define-public (resolve-alert (alert-id uint))
  (match (map-get? alerts { alert-id: alert-id })
    alert
      (begin
        (asserts!
          (or
            (is-authorized-operator)
            (is-dapp-owner (get dapp-id alert))
          )
          ERR-NOT-AUTHORIZED
        )
        (map-set alerts
          { alert-id: alert-id }
          (merge alert { resolved: true, resolved-at: block-height })
        )
        (ok true)
      )
    ERR-ALERT-NOT-FOUND
  )
)

;; ===========================
;; AUTONOMOUS REMEDIATION
;; ===========================

;; Adjust gas limit for a dApp (automated remediation)
(define-public (adjust-gas-limit (dapp-id uint) (new-gas-limit uint))
  (begin
    (asserts!
      (or (is-authorized-operator) (is-dapp-owner dapp-id))
      ERR-NOT-AUTHORIZED
    )
    (match (map-get? dapps { dapp-id: dapp-id })
      dapp
        (let (
          (old-limit (get gas-limit dapp))
          (action-index
            (match (map-get? dapp-remediation-count { dapp-id: dapp-id })
              rc (get count rc)
              u0
            )
          )
        )
          (map-set dapps
            { dapp-id: dapp-id }
            (merge dapp {
              gas-limit: new-gas-limit,
              last-updated: block-height
            })
          )
          (map-set remediation-log
            { dapp-id: dapp-id, action-index: action-index }
            {
              action-type: "gas-adjust",
              old-value: old-limit,
              new-value: new-gas-limit,
              performed-at: block-height,
              performed-by: tx-sender
            }
          )
          (map-set dapp-remediation-count
            { dapp-id: dapp-id }
            { count: (+ action-index u1) }
          )
          (ok true)
        )
      ERR-DAPP-NOT-FOUND
    )
  )
)

;; Log a transaction reroute remediation action
(define-public (log-reroute (dapp-id uint) (from-network uint) (to-network uint))
  (begin
    (asserts! (is-authorized-operator) ERR-NOT-AUTHORIZED)
    (asserts! (is-some (map-get? dapps { dapp-id: dapp-id })) ERR-DAPP-NOT-FOUND)
    (let (
      (action-index
        (match (map-get? dapp-remediation-count { dapp-id: dapp-id })
          rc (get count rc)
          u0
        )
      )
    )
      (map-set remediation-log
        { dapp-id: dapp-id, action-index: action-index }
        {
          action-type: "reroute",
          old-value: from-network,
          new-value: to-network,
          performed-at: block-height,
          performed-by: tx-sender
        }
      )
      (map-set dapp-remediation-count
        { dapp-id: dapp-id }
        { count: (+ action-index u1) }
      )
      (ok true)
    )
  )
)

;; Log a scaling action for a dApp
(define-public (log-scale-action (dapp-id uint) (old-scale uint) (new-scale uint))
  (begin
    (asserts! (is-authorized-operator) ERR-NOT-AUTHORIZED)
    (asserts! (is-some (map-get? dapps { dapp-id: dapp-id })) ERR-DAPP-NOT-FOUND)
    (let (
      (action-index
        (match (map-get? dapp-remediation-count { dapp-id: dapp-id })
          rc (get count rc)
          u0
        )
      )
    )
      (map-set remediation-log
        { dapp-id: dapp-id, action-index: action-index }
        {
          action-type: "scale",
          old-value: old-scale,
          new-value: new-scale,
          performed-at: block-height,
          performed-by: tx-sender
        }
      )
      (map-set dapp-remediation-count
        { dapp-id: dapp-id }
        { count: (+ action-index u1) }
      )
      (ok true)
    )
  )
)

;; ===========================
;; READ-ONLY FUNCTIONS
;; ===========================

;; Get full dApp info by ID
(define-read-only (get-dapp (dapp-id uint))
  (map-get? dapps { dapp-id: dapp-id })
)

;; Get dApp ID by name
(define-read-only (get-dapp-id-by-name (name (string-ascii 64)))
  (map-get? dapp-name-to-id { name: name })
)

;; Get performance metrics for a dApp
(define-read-only (get-metrics (dapp-id uint))
  (map-get? performance-metrics { dapp-id: dapp-id })
)

;; Get a specific alert
(define-read-only (get-alert (alert-id uint))
  (map-get? alerts { alert-id: alert-id })
)

;; Get a specific remediation log entry
(define-read-only (get-remediation-entry (dapp-id uint) (action-index uint))
  (map-get? remediation-log { dapp-id: dapp-id, action-index: action-index })
)

;; Get total remediation actions for a dApp
(define-read-only (get-remediation-count (dapp-id uint))
  (map-get? dapp-remediation-count { dapp-id: dapp-id })
)

;; Get monitoring node info
(define-read-only (get-node (node-id uint))
  (map-get? monitoring-nodes { node-id: node-id })
)

;; Check if an address is an authorized operator
(define-read-only (is-operator (address principal))
  (match (map-get? authorized-operators { operator: address })
    entry (get active entry)
    false
  )
)

;; Get current platform totals
(define-read-only (get-platform-stats)
  {
    total-dapps: (var-get total-dapps),
    total-nodes: (var-get total-nodes),
    total-alerts: (var-get total-alerts)
  }
)

;; Derive health status label from dApp ID
(define-read-only (get-health-status (dapp-id uint))
  (match (map-get? dapps { dapp-id: dapp-id })
    dapp (ok (score-to-status (get health-score dapp)))
    ERR-DAPP-NOT-FOUND
  )
)
